### PR TITLE
Added deinit for PBR maps

### PR DESCRIPTION
**Pull request by TotoShampoin**
In the previous PR, PBR materials were added. 

But I actually forgot to implement the deinit for the new map locations. I'm sorry for that.

This PR fixes that. But I would advise you check if I haven't forgotten something else

### CODE REVIEW

**Comment by chip2n** [comment]
No worries - looks good as far as I can tell. Do you have a .mtl file with PBR data laying around that we could add as a test (ideally one containing all new map locations)? That way the test allocator can prevent memory leak regressions.

**Comment by TotoShampoin** [comment]
[plateball.zip](https://github.com/user-attachments/files/18147652/plateball.zip)
Here is a 3D cubesphere (a sphere made out of a cube) that has PBR textures made in Blender.

However, there is 2 things I'm noticing:
- `norm` isn't being used for the normal map, it uses `map_Bump` instead
- `map_Bump` is used with texture arguments, and as far as I can tell, your lib might not account for that...

**Comment by chip2n** [comment]
I'll take a look at the file later this week. Using texture arguments for `map_Bump` sounds like something that should be supported if it isn't already, so thank you for the heads up!

**Comment by chip2n** [comment]
@TotoShampoin The following commit adds plateball.mtl as a test, and implements basic support for texture map arguments:

https://github.com/chip2n/zig-obj/commit/b94e9f8c417abd1f38b12b166f06f2647b1e4a10

The argument are just sent to the builder as a single string (which is stored as-is for the default implementation - although a custom builder which does something more fancy can be passed in).

There's probably a fair bit of other arguments available for the other keywords, but it's a start at least :)

**Pull request merged**
